package frc.robot.commands.climber;

import java.util.function.Supplier;

import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.controller.ProfiledPIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Transform2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.trajectory.TrapezoidProfile;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import org.littletonrobotics.junction.Logger;
import frc.robot.Constants.ClimbConstants;
import frc.robot.Constants.NavigationConstants;
import frc.robot.subsystems.Climber;
import frc.robot.subsystems.Drivetrain;

/**
 * ClimbCommandV2 — a rewrite of ClimbCommand focused on ACCURATE, REPEATABLE
 * positioning at the cage. The original ClimbCommand is left untouched so the
 * team can compare them side by side and switch over when V2 proves itself.
 *
 * ============================================================================
 * WHY A V2? WHAT WAS WRONG WITH V1? (read me first!)
 * ============================================================================
 * Last season odometry held about 3 inches of accuracy, but we need better
 * than that to line up the climber. Reviewing V1 (see REVIEW.md, findings
 * A2/A3) we found three problems:
 *
 * PROBLEM 1 — The "approach" phase never ran.
 *   V1's comments promised: align -> extend -> drive forward 20" -> climb.
 *   But the line of code that ENTERS the approach phase was commented out,
 *   so the robot skipped the forward move entirely and climbed from wherever
 *   it happened to be. The 20-inch target position was computed and then
 *   never used. V2 implements the full sequence for real.
 *
 * PROBLEM 2 — "Arrived" was way too forgiving.
 *   V1 declared success the instant the robot wandered inside a 7 cm (~2.75")
 *   circle — even for a single sensor cycle. One noisy reading could pass.
 *   V2 tightens the circle to 3 cm AND requires the robot to STAY inside it
 *   for 0.1 seconds before we believe it (a "dwell check").
 *
 * PROBLEM 3 — The robot crashed to a stop at the end.
 *   V1 used bare P-controllers, so the robot decelerated only because the
 *   error shrank — it tended to overshoot, oscillate, and settle late.
 *   V2 uses a trapezoid motion profile (see below) so the robot plans a
 *   smooth accelerate-cruise-decelerate speed pattern and arrives gently,
 *   like MA team 6328's DriveToPose does.
 *
 * HOW THE MOTION PROFILE WORKS (the cool part):
 *   Instead of asking "how far am I? -> how hard should I push?", a trapezoid
 *   profile plans the whole speed plan ahead: ramp UP to a cruise speed, hold,
 *   then ramp DOWN so you arrive exactly at the target with zero speed.
 *   The shape of speed-vs-time looks like a trapezoid (flat top), hence the
 *   name. Because the deceleration is planned, not improvised, the robot
 *   settles quickly and repeatably — that's what buys us tight tolerances.
 *
 * NOTE ON ALLIANCE POSES: this command drives to whatever pose the dashboard
 * chooser supplies, taken as absolute field coordinates. Make sure the RED
 * poses in Constants.ClimbConstants are generated by proper alliance flipping
 * (REVIEW.md finding A4) — V2 deliberately does no mirroring of its own.
 * ============================================================================
 */
public class ClimbCommandV2 extends Command {

    // ========================================================================
    // TUNING CONSTANTS — start here when tuning on the bench!
    // All speeds/accelerations are deliberately gentle: precision first,
    // speed later. Log everything (bottom of execute()) and tune with data.
    // ========================================================================

    /** How close we must get, in meters. 0.03 m = ~1.2 inches. (V1: 0.07 m) */
    private static final double kPositionToleranceMeters = 0.03;
    /** How straight we must be pointed, in degrees. (V1: 5 degrees) */
    private static final double kHeadingToleranceDegrees = 2.0;

    /**
     * Dwell time: the robot must stay inside tolerance this long before we
     * say "arrived". One lucky noisy cycle doesn't count anymore.
     */
    private static final double kArrivalDwellSeconds = 0.10;

    // --- Translation (forward/backward/left/right) motion profile ---
    /** Cruise speed while approaching, m/s. (Same gentle speed as V1.) */
    private static final double kDriveMaxVelocity = ClimbConstants.kDriveMaxSpeedMetersPerSecond; // 0.5
    /** Acceleration limit, m/s^2. Low = smooth starts, no wheel slip. */
    private static final double kDriveMaxAcceleration = 1.0;

    // --- Rotation motion profile ---
    private static final double kThetaMaxVelocityRadPerSec = Math.toRadians(45);
    private static final double kThetaMaxAccelerationRadPerSec2 = Math.toRadians(90);

    // --- Feedback gains (fine corrections on top of the planned profile) ---
    /** Translation P gain: m/s of correction per meter of remaining error. */
    private static final double kDriveP = 3.0;
    /** Translation D gain: damps overshoot by resisting fast error changes. */
    private static final double kDriveD = 0.1;
    /** Heading P gain: rad/s of correction per radian of heading error. */
    private static final double kThetaP = 3.0;
    private static final double kThetaD = 0.1;

    /**
     * Feedforward blend zone (meters): far away we fully trust the profile's
     * planned speed; inside this zone we fade it out so the PID has the final
     * word near the goal. (Pattern borrowed from MA 6328's DriveToPose.)
     */
    private static final double kLinearFFMinRadius = 0.01;
    private static final double kLinearFFMaxRadius = 0.05;

    // --- Per-phase watchdogs (seconds). Safety nets, not race strategies. ---
    private static final double kAlignTimeoutSeconds = 5.0;
    private static final double kExtendTimeoutSeconds = 6.0;
    private static final double kApproachTimeoutSeconds = 3.0;
    private static final double kClimbTimeoutSeconds = 8.0;

    /** Climber encoder reading (rotations) close enough to call "climbed". Same rule as V1. */
    private static final double kClimbedEncoderThreshold = 5.0;

    // ========================================================================
    // PHASE MACHINE
    // The documented-but-broken V1 sequence, actually implemented this time:
    //   ALIGNING_TO_START  -> drive to the chosen start pose
    //   EXTENDING_AT_START -> stop, raise the climber hook
    //   APPROACHING_CLIMB  -> drive forward so the hook passes over the cage
    //                         (early-out if the proximity sensor sees the plate)
    //   CLIMBING           -> retract the climber and lift off
    //   FINISHED
    // ========================================================================
    private enum Phase {
        ALIGNING_TO_START, EXTENDING_AT_START, APPROACHING_CLIMB, CLIMBING, FINISHED
    }

    private static final String DASHBOARD_KEY_PREFIX = "ClimbCommandV2/";

    private final Drivetrain drivetrain;
    private final Climber climber;
    private final Supplier<Pose2d> selectedStartPoseSupplier;

    // Motion controllers. The theta controller is "profiled" (it plans its own
    // trapezoid for heading); translation uses an explicit TrapezoidProfile below.
    private final PIDController driveController = new PIDController(kDriveP, 0.0, kDriveD);
    private final ProfiledPIDController thetaController = new ProfiledPIDController(
        kThetaP, 0.0, kThetaD,
        new TrapezoidProfile.Constraints(kThetaMaxVelocityRadPerSec, kThetaMaxAccelerationRadPerSec2));

    // One timer, restarted at EVERY phase change. (V1 shared one timer across
    // phases with a stop/reset/restart dance that was one edit away from a bug.)
    private final Timer phaseTimer = new Timer();
    private final Timer loopTimer = new Timer();

    private Phase phase = Phase.ALIGNING_TO_START;
    private Phase lastLoggedPhase = null;
    private Pose2d startPose = ClimbConstants.kBlueLeftStartPose;
    private Pose2d approachPose = ClimbConstants.kBlueLeftStartPose;

    // Dwell tracking: seconds spent continuously inside tolerance.
    private double dwellSeconds = 0.0;
    private double lastDistanceMeters = Double.NaN;

    public ClimbCommandV2(Drivetrain drivetrain, Climber climber, Supplier<Pose2d> selectedStartPoseSupplier) {
        this.drivetrain = drivetrain;
        this.climber = climber;
        this.selectedStartPoseSupplier = selectedStartPoseSupplier;

        // Heading wraps around: -179 deg and +179 deg are neighbors, not enemies.
        thetaController.enableContinuousInput(-Math.PI, Math.PI);
        thetaController.setTolerance(Math.toRadians(kHeadingToleranceDegrees));

        addRequirements(drivetrain, climber);
    }

    @Override
    public void initialize() {
        Pose2d selected = selectedStartPoseSupplier.get();
        startPose = selected != null ? selected : ClimbConstants.kBlueLeftStartPose;

        // The approach point sits kDriveForwardDistanceMeters "ahead" of the
        // start pose, along the start pose's own heading. transformBy() applies
        // the offset in the pose's local frame, which is exactly what we want.
        approachPose = startPose.transformBy(new Transform2d(
            ClimbConstants.kDriveForwardDistanceMeters, 0.0, new Rotation2d()));

        phase = Phase.ALIGNING_TO_START;
        lastLoggedPhase = null;      // forces the first phase-transition log line
        dwellSeconds = 0.0;
        lastDistanceMeters = Double.NaN;

        climber.stop();

        // Reset all controller memory from any previous run.
        driveController.reset();
        thetaController.reset(
            drivetrain.getPose().getRotation().getRadians(),
            drivetrain.getChassisSpeeds().omegaRadiansPerSecond);

        phaseTimer.restart();
        loopTimer.restart();

        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "Running", true);
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "StartPose", startPose);
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "ApproachPose", approachPose);
        SmartDashboard.putBoolean(DASHBOARD_KEY_PREFIX + "Running", true);
        SmartDashboard.putString(DASHBOARD_KEY_PREFIX + "StartPose", formatPose(startPose));
        SmartDashboard.putString(DASHBOARD_KEY_PREFIX + "ApproachPose", formatPose(approachPose));
    }

    @Override
    public void execute() {
        double dt = loopTimer.get();   // seconds since previous execute() cycle
        loopTimer.reset();
        if (dt <= 0 || dt > 0.5) {
            dt = 0.02;                 // sanity fallback: one robot loop period
        }

        switch (phase) {
            case ALIGNING_TO_START -> {
                boolean arrived = driveToPose(startPose, dt);
                if (arrived) {
                    // Real progress beyond V1: we now actually WAIT until we are
                    // aligned BEFORE raising the hook (V1 raised it immediately).
                    transitionTo(Phase.EXTENDING_AT_START);
                } else if (phaseTimer.hasElapsed(kAlignTimeoutSeconds)) {
                    // Watchdog: something blocked alignment (bad pose estimate?).
                    // Proceed anyway and let the driver see the warning — climbing
                    // slightly misaligned beats freezing mid-sequence.
                    warn("Align timed out after " + kAlignTimeoutSeconds + "s; proceeding anyway");
                    transitionTo(Phase.EXTENDING_AT_START);
                }
            }
            case EXTENDING_AT_START -> {
                // Hold position while the hook comes up.
                drivetrain.setChassisSpeeds(new ChassisSpeeds());
                climber.extendClimber(); // self-stops when its limits trip

                if (climber.isExtendLimitReached()) {
                    transitionTo(Phase.APPROACHING_CLIMB);
                } else if (phaseTimer.hasElapsed(kExtendTimeoutSeconds)) {
                    warn("Extend timed out after " + kExtendTimeoutSeconds + "s; proceeding anyway");
                    transitionTo(Phase.APPROACHING_CLIMB);
                }
            }
            case APPROACHING_CLIMB -> {
                // THE MOVE THAT NEVER RAN IN V1. Drive forward so the extended
                // hook passes over the cage bar. The proximity sensor can end
                // this phase early when it physically detects the plate.
                boolean arrived = driveToPose(approachPose, dt);
                if (arrived || climber.isClimbPlateDetected()) {
                    if (!arrived) {
                        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "ApproachEarlyOut", "PlateDetected");
                    }
                    transitionTo(Phase.CLIMBING);
                } else if (phaseTimer.hasElapsed(kApproachTimeoutSeconds)) {
                    warn("Approach timed out after " + kApproachTimeoutSeconds + "s; climbing anyway");
                    transitionTo(Phase.CLIMBING);
                }
            }
            case CLIMBING -> {
                // Stop driving and pull ourselves up. retractClimber() self-stops
                // on its reverse limit / current spike, exactly like V1.
                drivetrain.setChassisSpeeds(new ChassisSpeeds());
                climber.retractClimber();

                if (Math.abs(climber.getEncoderPosition()) <= kClimbedEncoderThreshold
                    || climber.isRetractLimitReached()) {
                    transitionTo(Phase.FINISHED);
                } else if (phaseTimer.hasElapsed(kClimbTimeoutSeconds)) {
                    warn("Climb timed out after " + kClimbTimeoutSeconds + "s; stopping");
                    climber.stop();
                    transitionTo(Phase.FINISHED);
                }
            }
            case FINISHED -> {
                // Nothing to do; isFinished() ends the command.
            }
        }

        publishTelemetry();
    }

    @Override
    public void end(boolean interrupted) {
        drivetrain.setChassisSpeeds(new ChassisSpeeds());
        climber.stop();

        String result = interrupted ? "Interrupted in " + phase : "Completed";
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "Running", false);
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "LastResult", result);
        SmartDashboard.putBoolean(DASHBOARD_KEY_PREFIX + "Running", false);
        SmartDashboard.putString(DASHBOARD_KEY_PREFIX + "LastResult", result);
    }

    @Override
    public boolean isFinished() {
        return phase == Phase.FINISHED;
    }

    /**
     * Drives toward the goal pose using the profiled-close strategy.
     *
     * @return true when the robot has been inside tolerance for the full
     *         dwell time (not just for one lucky cycle).
     */
    private boolean driveToPose(Pose2d goal, double dt) {
        Pose2d currentPose = drivetrain.getPose();

        // ---- Translation: trapezoid profile on DISTANCE TO GOAL ----
        Translation2d toGoal = goal.getTranslation().minus(currentPose.getTranslation());
        double distance = toGoal.getNorm();

        // Estimate how fast the distance is shrinking (finite difference of the
        // measurement). This tells the profile where we currently are on its plan.
        double closingSpeed = Double.isNaN(lastDistanceMeters)
            ? 0.0
            : (lastDistanceMeters - distance) / dt;
        lastDistanceMeters = distance;

        // Run the profile: it answers "where SHOULD I be by now?" given where I
        // am and how fast I'm approaching. Then the PID cleans up the leftover.
        TrapezoidProfile profile = new TrapezoidProfile(new TrapezoidProfile.Constraints(
            kDriveMaxVelocity, kDriveMaxAcceleration));
        TrapezoidProfile.State profileSetpoint = profile.calculate(
            dt, new TrapezoidProfile.State(distance, -closingSpeed), new TrapezoidProfile.State(0.0, 0.0));

        double pidSpeed = driveController.calculate(distance, profileSetpoint.position);

        // Feedforward fade: far from the goal, follow the profile's planned
        // speed; close in, fade it out and let the PID land us precisely.
        double ffScaler = MathUtil.clamp(
            (distance - kLinearFFMinRadius) / (kLinearFFMaxRadius - kLinearFFMinRadius), 0.0, 1.0);
        double forwardSpeed = pidSpeed + profileSetpoint.velocity * ffScaler;

        // Convert "speed along the line to the goal" into field X/Y velocities.
        double vx = 0.0;
        double vy = 0.0;
        if (distance > 1e-4) { // avoid dividing by ~zero when basically there
            vx = forwardSpeed * (toGoal.getX() / distance);
            vy = forwardSpeed * (toGoal.getY() / distance);
        }

        // ---- Heading: profiled PID straight to the goal heading ----
        double omega = thetaController.calculate(
            currentPose.getRotation().getRadians(), goal.getRotation().getRadians());

        // Ship it: field-relative X/Y/omega converted to wheel commands.
        drivetrain.setChassisSpeeds(ChassisSpeeds.fromFieldRelativeSpeeds(
            vx, vy, omega, currentPose.getRotation()));

        // ---- Arrival check with DWELL: must stay good for kArrivalDwellSeconds ----
        double headingErrorDeg = Math.abs(MathUtil.inputModulus(
            currentPose.getRotation().minus(goal.getRotation()).getDegrees(), -180.0, 180.0));
        boolean insideTolerance =
            distance <= kPositionToleranceMeters && headingErrorDeg <= kHeadingToleranceDegrees;

        dwellSeconds = insideTolerance ? dwellSeconds + dt : 0.0;

        // Per-cycle logging so bench tuning is data-driven, not vibes-driven.
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "Goal", goal);
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "DistanceErrorMeters", distance);
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "HeadingErrorDegrees", headingErrorDeg);
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "ProfileSetpointSpeed", profileSetpoint.velocity);
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "CommandedForwardSpeed", forwardSpeed);
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "CommandedOmega", omega);
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "DwellSeconds", dwellSeconds);
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "InsideTolerance", insideTolerance);

        return dwellSeconds >= kArrivalDwellSeconds;
    }

    /** Central place for phase changes: restarts the watchdog and logs the hop. */
    private void transitionTo(Phase next) {
        phase = next;
        phaseTimer.restart();
        dwellSeconds = 0.0;
        lastDistanceMeters = Double.NaN; // fresh approach for the new leg
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "PhaseTransitionAt",
            Timer.getFPGATimestamp());
    }

    private void warn(String message) {
        System.out.println("[ClimbCommandV2] WARNING: " + message);
        Logger.recordOutput(DASHBOARD_KEY_PREFIX + "LastWarning", message);
    }

    private void publishTelemetry() {
        // Log the phase whenever it changes (and once at startup) so match logs
        // read like a story instead of a wall of identical lines.
        if (phase != lastLoggedPhase) {
            Logger.recordOutput(DASHBOARD_KEY_PREFIX + "Phase", phase.name());
            SmartDashboard.putString(DASHBOARD_KEY_PREFIX + "Phase", phase.name());
            lastLoggedPhase = phase;
        }
        SmartDashboard.putNumber(DASHBOARD_KEY_PREFIX + "PhaseTimeSeconds", phaseTimer.get());
        SmartDashboard.putBoolean(DASHBOARD_KEY_PREFIX + "ClimbPlateDetected", climber.isClimbPlateDetected());
        SmartDashboard.putNumber(DASHBOARD_KEY_PREFIX + "ClimberEncoder", climber.getEncoderPosition());
    }

    private String formatPose(Pose2d pose) {
        return String.format("(%.3f, %.3f, %.1f deg)",
            pose.getX(), pose.getY(), pose.getRotation().getDegrees());
    }
}
